version: '0.2'
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - acubismmotion
  - airi
  - airi-vtuber
  - Attributify
  - Ayaka
  - bumpp
  - composables
  - csmmap
  - csmvector
  - cubismbreath
  - cubismdebug
  - cubismdefaultparameterid
  - cubismeyeblink
  - cubismmatrix44
  - cubismmoc
  - cubismmodelsettingjson
  - cubismmotionqueuemanager
  - cubismusermodel
  - cubismviewmatrix
  - demi
  - elevenlabs
  - hiyori
  - iconify
  - intlify
  - kwaa
  - live2dcubismcore
  - live2dcubismframework
  - Myriam
  - Neko
  - nekomeowww
  - Neuro
  - Neuro-sama
  - nuxi
  - nuxt
  - nuxtjs
  - ofetch
  - openai
  - pinia
  - pixi
  - rehype
  - shiki
  - shikijs
  - sizecheck
  - taze
  - unhead
  - unocss
  - unplugin
  - vueuse
ignoreWords: []
import: []
