version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - airi-vtuber
  - composables
  - elevenlabs
  - hiyori
  - iconify
  - Myriam
  - nekomeowww
  - Neuro
  - nuxi
  - nuxt
  - nuxtjs
  - ofetch
  - openai
  - pinia
  - pixi
  - rehype
  - unocss
  - vueuse
  - Neuro-sama
ignoreWords: []
import: []
