version: '0.2'
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - airi-vtuber
  - composables
  - elevenlabs
  - hiyori
  - iconify
  - kwaa
  - Myriam
  - nekomeowww
  - Neuro
  - Neuro-sama
  - nuxi
  - nuxt
  - nuxtjs
  - ofetch
  - openai
  - pinia
  - pixi
  - rehype
  - unocss
  - vueuse
  - live2dcubismcore
  - live2dcubismframework
  - cubismmatrix44
  - csmvector
  - cubismviewmatrix
  - cubismdefaultparameterid
  - cubismmodelsettingjson
  - cubismbreath
  - cubismeyeblink
  - cubismusermodel
  - acubismmotion
  - cubismmotionqueuemanager
  - csmmap
  - cubismdebug
  - cubismmoc
ignoreWords: []
import: []
