version: '0.2'
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - composables
  - elevenlabs
  - hiyori
  - Myriam
  - nekomeowww
  - Neuro
  - ofetch
  - openai
  - pinia
  - pixi
  - rehype
  - vueuse
  - airi-vtuber
ignoreWords: []
import: []
