version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - composables
  - elevenlabs
  - hiyori
  - Myriam
  - Neuro
  - ofetch
  - openai
  - pinia
  - pixi
  - rehype
  - vueuse
ignoreWords: []
import: []
